//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "characters")]
pub struct Model {
    pub id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub name: String,
    pub class: String,
    pub item_level: i32,
    pub last_updated: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::guildmates::Entity",
        from = "Column::Id",
        to = "super::guildmates::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Guildmates,
}

impl Related<super::guildmates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Guildmates.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
