//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

pub mod prelude;

pub mod characters;
pub mod guildmates;
pub mod lobby;
pub mod lobby_player;
pub mod sea_orm_active_enums;
pub mod seaql_migrations;
pub mod servers;

pub use sea_orm;

use sea_orm::{Linked, RelationTrait};
use prelude::*;

impl Linked for Characters {
    type FromEntity = Lobby;

    type ToEntity = Characters;

    fn link(&self) -> Vec<sea_orm::LinkDef> {
        vec![
            lobby::Relation::LobbyPlayer.def(),
            lobby_player::Relation::Characters.def()
        ]
    }
}